### ISSUE TITLE
Cannot find module runtime error

### ISSUE THREAD

**Issue by deepforest** [willsoto/nestjs-objection#767]
Using this great module with:
```
"@nestjs/common": "^7.0.0",
"@nestjs/core": "^7.0.0",
"@nestjs/platform-express": "^7.0.0",
"@willsoto/nestjs-objection": "^4.0.2",
"knex": "^0.21.6",
"objection": "^2.2.3",
"pg": "^8.4.1",
```

I'm getting the following error when `npm start`:

```
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '@willsoto/nestjs-objection/typings/module'
Require stack:
- /home/xyz/develop/aaa/Backend/services/bbb/dist/app.module.js
- /home/xyz/develop/aaa/Backend/services/bbb/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/xyz/develop/aaa/Backend/services/bbb/dist/app.module.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xyz/develop/aaa/Backend/services/bbb/dist/app.module.js',
    '/home/xyz/develop/aaa/Backend/services/bbb/dist/main.js'
  ]
}
```

Note that i'm decorating the app module like so:

```
import { Module } from '@nestjs/common';
import { ObjectionModule } from '@willsoto/nestjs-objection/typings/module';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    ObjectionModule.register({
      config: {
        client: 'postgres',
        useNullAsDefault: true,
        connection: {
          host: process.env.DB_HOST,
          database: process.env.DB_INSTANCE,
          user: process.env.DB_USER,
          password: process.env.DB_PASS,
        },
      },
    })
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by willsoto** [comment]
Not sure why you are trying to import from `import { ObjectionModule } from '@willsoto/nestjs-objection/typings/module';`. Just change the import to: `import { ObjectionModule } from '@willsoto/nestjs-objection';`

**Comment by deepforest** [comment]
My bad! vscode imported that to me automatically, didn't notice.
Thanks! it works just fine. False alarm.
